---
title: "p8105_hw3_ys3875"
author: "Yanhao Shen"
date: "2024-10-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
```

Q2.
```{r}
demographic_data =
  read_csv("nhanes_covar.csv", na = c('NA', ' ', '.'), col_names = TRUE, skip = 4) |>
  drop_na() |>
  janitor::clean_names() |>
  filter(age>=21) |>
  mutate(
    sex=
      case_match(
        sex,
        1~ 'male',
        2~ 'female'),
    education=
      case_match(
        education,
        1~ 'Less than high school',
        2~ 'High school equivalent',
        3~ 'More than high school'),
    sex = as.factor(sex),
    education = as.factor(education)
  )

accelerometer_data = 
  read_csv("nhanes_accel.csv", na=c('NA',' ','.')) |>
  drop_na() |>
  janitor::clean_names()
```
```{r}
dd_table <- demographic_data |>
  group_by(education,sex) |>
  summarise(count=n(), .groups = 'drop')|>
  spread(key = sex, value=count,fill = 0)
dd_table

dd_plot <- demographic_data |>
  ggplot(aes(x=education, y=age, fill=sex))+
  geom_violin()+
  theme_minimal()
dd_plot
```
Relatively, there are more men going to high school than women, for less than and more that high school, the number are pretty close. \
For both man and women, the age lies averagely for high school equivalent. There are less young energy(<30) for less than high school, while for more than high school, the condition is exactly the opposite.
```{r}
total_activity_data <- 
  accelerometer_data |>
  mutate(total_activity= rowSums(select(.,2:1441)), na.rm=TRUE)

```

